sudo: false
language: python
python:
  - "3.5"
  - "3.6"
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
addons:
  apt:
    packages:
      - python-scipy
      - python-matplotlib
dist: trusty
install:
  - deactivate
  - virtualenv --system-site-packages testvenv
  - source testvenv/bin/activate
  - pip install nose
script: nosetests

notifications:
  email: false
